# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShotPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_started', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('shot_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='annotate.Shot')),
                ('shot_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='annotate.Shot')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('p_values', models.TextField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='shotpair',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotate.Video'),
        ),
        migrations.AddField(
            model_name='shot',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotate.Video'),
        ),
        migrations.AddField(
            model_name='annotator',
            name='last_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotate.Video'),
        ),
        migrations.AddField(
            model_name='annotator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
