# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shotpair',
            name='annotation_started',
            field=models.DateTimeField(null=True),
        ),
    ]
