# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0003_auto_20160216_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotator',
            name='country',
            field=django_countries.fields.CountryField(default='FI', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annotator',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('another', 'Another/prefer not to disclose')], default='male', max_length=10),
            preserve_default=False,
        ),
    ]
