# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0005_shotpair_annotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shotpair',
            name='annotation',
        ),
    ]
