# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0006_remove_shotpair_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='number',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='number',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
