# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0007_auto_20160224_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='annotation_rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
