# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0009_auto_20160225_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='p_values',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
