# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0011_auto_20160225_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotator',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='annotator',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='annotator',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('another', 'Another/prefer not to disclose')], max_length=10, null=True),
        ),
    ]
