# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0012_auto_20160226_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='image_filename',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
