# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0013_shot_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotator',
            name='annotation_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
