# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-06 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0014_annotator_annotation_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(default=0)),
                ('annotation_round', models.IntegerField(default=0)),
                ('when', models.DateTimeField(null=True)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotate.Annotator')),
                ('shot_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='annotate.Shot')),
                ('shot_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='annotate.Shot')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='annotate.Video')),
            ],
        ),
        migrations.CreateModel(
            name='LogRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_round', models.IntegerField(default=0)),
                ('when', models.DateTimeField(null=True)),
                ('p_values', models.TextField(blank=True, default='', max_length=5000)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='annotate.Video')),
            ],
        ),
    ]
